#!/usr/bin/env bash
#
# Run the full benchmark suite and emit a Markdown report.
#
# Steps:
#   1. Ensure the project-local venv exists (and numpy is in it).
#   2. Capture hardware/software fingerprint.
#   3. Run bench/run.php → numphp.jsonl
#   4. Run bench/run.py  → numpy.jsonl
#   5. Run bench/compare.py to combine into a Markdown table.
#   6. Emit the full report (fingerprint + table + diagnostics).
#
# Output: report Markdown to stdout. Intermediate JSONL goes to
# bench/last-run/ so a subsequent comparison or debug pass can use it.
#
# Usage:
#   bash bench/run.sh                 # full suite
#   bash bench/run.sh --tiny          # smoke (one tiny scenario each)

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
TINY=""
if [[ "${1-}" == "--tiny" ]]; then
    TINY="--tiny"
fi

OUT="$ROOT/bench/last-run"
mkdir -p "$OUT"

VENV="$ROOT/bench/.venv"
SO="$ROOT/modules/numphp.so"

if [[ ! -d "$VENV" ]]; then
    echo "[setup] creating bench/.venv and installing numpy..." >&2
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install --quiet --upgrade pip
    "$VENV/bin/pip" install --quiet numpy
fi

if [[ ! -f "$SO" ]]; then
    echo "[error] $SO not found — run 'phpize && ./configure --enable-numphp && make' first." >&2
    exit 1
fi

if ! "$VENV/bin/python" -c "import numpy" 2>/dev/null; then
    echo "[setup] numpy missing in venv, installing..." >&2
    "$VENV/bin/pip" install --quiet numpy
fi

echo "[bench] capturing fingerprint..." >&2
bash bench/fingerprint.sh > "$OUT/fingerprint.json"

echo "[bench] running numphp..." >&2
php -d extension="$SO" bench/run.php $TINY > "$OUT/numphp.jsonl"

echo "[bench] running numpy..." >&2
"$VENV/bin/python" bench/run.py $TINY > "$OUT/numpy.jsonl"

echo "[bench] comparing..." >&2
table=$("$VENV/bin/python" bench/compare.py "$OUT/numphp.jsonl" "$OUT/numpy.jsonl")

# Emit the full report.
cat <<EOF
# numphp vs NumPy — benchmark report

_Generated by \`bash bench/run.sh\`. Reproducible: re-run on the same
hardware to confirm; commit a fresh \`docs/benchmarks.md\` if you'd
like a permanent record._

## Fingerprint

\`\`\`json
$(cat "$OUT/fingerprint.json")
\`\`\`

## Results

$table

## How to read this

- **ratio** is \`numphp_median / numpy_median\`. Values **>1** mean
  numphp is slower; **<1** means faster; **~1** means parity.
- The matmul scenarios should be near-parity since both engines call
  the same OpenBLAS routine. Significant divergence there points at
  layout / copy overhead.
- Element-wise scenarios where NumPy is faster reflect NumPy's more
  vectorised inner loops; numphp uses a generic nd-iterator.
- \`fromArray\` / \`toArray\` are interop costs — building a numphp
  array from a nested PHP array (or going back) is unavoidable
  bridging work that fast paths can't hide.
- \`slice (view creation)\` should be sub-millisecond on both sides
  — both engines return zero-copy views, the timing measures pointer
  arithmetic + metadata setup.

## Reproduce

\`\`\`bash
cd $ROOT
phpize && ./configure --enable-numphp
make CFLAGS="-Wall -Wextra -O2 -g"
bash bench/run.sh
\`\`\`

The first \`bench/run.sh\` invocation creates \`bench/.venv\` and
\`pip install\`s NumPy into it (gitignored). Subsequent runs reuse
the venv.
EOF
